USER_FEATURES = [
       'user_is_mom',
       'user_is_pregnant',
       'user_is_trying',
       'user_country_code',
       'days_since_user_account_creation',
       'user_pregnancy_current_day',
       'user_pregnancy_current_week',
       'user_pregnancy_current_month',
       'user_pregnancy_current_trimester',
       'platform',
       'user_department',
       'user_followings_count',
       'user_posts_count',
       'user_received_comments_count',
       'user_pictures_count',
       'user_likes_count',
       'user_children_count',
]

USER_POST_FEATURES = [
       'user_post_last_1d_views_count',
       'user_post_last_1d_clicks_count',
       'user_post_last_1d_ratio',
       'user_post_last_7d_views_count',
       'user_post_last_7d_clicks_count',
       'user_post_last_7d_ratio',
       'user_post_last_28d_views_count',
       'user_post_last_28d_clicks_count',
       'user_post_last_28d_ratio'
]

POST_FEATURES = [
       'post_age_in_minutes',
       'author_children_count',
       'post_comments_count',
       'post_likes_count',
       'survey_answers_count',
       'has_picture',
       'has_text',
       'has_video',
       'author_department',
       'author_age',
       'author_amenorrhea_week',
       'author_has_same_age_children',
       'author_has_same_age_month_children',
       'author_has_older_children',
       'post_last_1d_views_count',
       'post_last_1d_clicks_count',
       'post_last_1d_ratio',
       'post_last_7d_views_count',
       'post_last_7d_clicks_count',
       'post_last_7d_ratio',
       'post_last_28d_views_count',
       'post_last_28d_clicks_count',
       'post_last_28d_ratio'
]
